### ISSUE TITLE
Retry doesn't work on data download section

### ISSUE THREAD

**Issue by evilbunny2008** [glennmckechnie/weewx-uradmon#3]
I'm not 100% sure how to fix this, or I would have filed a PR.

The retry part of the data download doesn't work. I get the following in the log:

```
Sep 14 19:20:15 shed-rock64 weewx[26208]: uradmon: connection attempt 1 to 192.168.2.17
Sep 14 19:20:25 shed-rock64 weewx[26208]: uradmon: error (timed out) on attempt 1 to 192.168.2.17
Sep 14 19:20:25 shed-rock64 weewx[26208]: uradmon: connection attempt 2 to 192.168.2.17

```
Although for reasons I don't understand I can't get it to time out using wget etc, but it was happening in weewx.

Hopefully this makes sense, cause I'm stumped.

**Comment by glennmckechnie** [comment]
You're not alone.
I couldn't pin it down either, there's a  vague, handwaving note in the comment about cronjobs etc and  DDOSing it which is probably why you tried wget? FWIW, I just ran a 5 sec wget loop and it didn't fail for me either. The cronjob was when I was calling the original script (1st standalone python version of uradmon) and it settled down considerably after I stopped that.
If I try from firefox or opera I get the first load  but it tends to  timeout after that (maybe they've been up too long).
Mine is the WiFi version.

It will try 3 times before bailng so I'm guessing that it succeeded on the 3rd, as you don't include it in the snippet?
Checking my logs I have 70 failures (where it hit the 3 limit) in 6 days. I use a one minute archive interval.

Keep an eye on it and if you have any inspiration then I'm all ears.

Actually, now that that it's happening with someone else (2 data points) it's probably worth bringing it up with Radu. I'll do that.

I wonder if Liz has the issue?

**Comment by evilbunny2008** [comment]
I installed your skin the other day and thought I must have failed setting something up, but next morning it was working and I hadn't changed a thing.

As for the next lines after the first try, it got on with other weewx'y things, no data received and no second attempt etc...

I'm using the wifi version too.

**Comment by glennmckechnie** [comment]
Argh. I've foobar'd the logic. I'll stare at the code for a while.

**Comment by lizdodd** [comment]
On Sun, 16 Sep 2018 00:26:03 +0000 (UTC)
Glenn <notifications@github.com> wrote:

> You're not alone.
> I couldn't pin it down either, there's a  vague, handwaving note in
> the comment about cronjobs etc and  DDOSing it which is probably why
> you tried wget? FWIW, I just ran a 5 sec wget loop and it didn't fail
> for me either. The cronjob was when I was calling the original script
> (1st standalone python version of uradmon) and it settled down
> considerably after I stopped that. If I try from firefox or opera I
> get the first load  but it tends to  timeout after that (maybe
> they've been up too long). Mine is the WiFi version.
> 
> It will try 3 times before bailng so I'm guessing that it succeeded
> on the 3rd, as you don't include it in the snippet? Checking my logs
> I have 70 failures (where it hit the 3 limit) in 6 days. I use a one
> minute archive interval.
> 
> Keep an eye on it and if you have any inspiration then I'm all ears.
> 
> Actually, now that that it's happening with someone else (2 data
> points) it's probably worth bringing it up with Radu. I'll do that.
> 
> I wonder if Liz has the issue?
> 

I have a wired version.
When it was moved it got a changed IP address (until I had serious
words with the DHCP server) and then I was getting three failures in a
row.
I have no idea if the second or third try would work if there was an
intermittent problem with connection.

Liz

**Comment by glennmckechnie** [comment]
Okay, I'll review this again but the logic is fixed and does work for a timeout (or similar error). Backoff timing needs checking/reworking but it shouldn't leave you in the lurch any more.

Obviously - let me know if it fails miserably. also if you start getting timeout errors as that will be the old problem reservicing (now that it's allowed to retry!).

**Comment by glennmckechnie** [comment]
[That's on the dev tree.](https://github.com/glennmckechnie/weewx-uradmon/tree/dev)

**Comment by evilbunny2008** [comment]
> [That's on the dev tree.](https://github.com/glennmckechnie/weewx-uradmon/tree/dev)

I just downloaded it, but it didn't time out yet, will keep watching the logs

**Comment by evilbunny2008** [comment]
The code does report that it retries, but it still fails occasionally on all 3 attempts, which is most annoying...

**Comment by glennmckechnie** [comment]
Just checked mine and there are 7 missed attempts since the logs rotated at 6:25am
Interestingly enough 2 just happened which capture a time out with a response on the 2nd attempt, and a full timeout (complete fail) 60 seconds later.

(urad_debug = True)

copygenerator: copied 8 files to /var/www/html/weewx/wxobs
uradmon: error (timed out) on attempt 1 to 192.168.0.235
uradmon: 192.168.0.235 responded on attempt 2
uradmon:  record is {'uvolt': 378, 'upm25': 12, 'unoise': None, 'uch2o': 0.03, 'uhum': 47.7, 'uvoc': 50393, 'usUnits': 16, 'uptime': 1004827,
 'ucpm': 0, 'uco2': 955, 'interval': 1, 'dateTime': 1537149155, 'utemp': 23.35, 'upres': 96705}
manager: Added record 2018-09-17 11:52:35 AEST (1537149155) to database 'uradmon.sdb'
manager: Added record 2018-09-17 11:52:35 AEST (1537149155) to daily summary in 'uradmon.sdb'
[...]
manager: Added record 2018-09-17 11:52:00 AEST (1537149120) to daily summary in 'sqlitedupe.sdb'
manager: Added record 2018-09-17 11:52:36 AEST (1537149156) to database 'pmon+.sdb'
uradmon: error (timed out) on attempt 1 to 192.168.0.235
uradmon: error (timed out) on attempt 2 to 192.168.0.235
uradmon: error (timed out) on attempt 3 to 192.168.0.235
uradmon: No data fetched, after 2 attempts to 192.168.0.235

So, the retries are happening - and can succeed if the unit recovers. The problem would seem to be with the unit. I'll make that post to Radu and wait for him to respond.

I'll push a minor update that clarifies the log messages - they are a little confusing at the moment :-)

Liz - how  is you're cabled version going, any timeouts?

**Comment by glennmckechnie** [comment]
Posted to the uradmon forum as  [Local access: unit can fail to respond to local json queries](https://www.uradmonitor.com/topic/local-access-unit-can-fail-to-respond-to-local-json-queries/)

**Comment by lizdodd** [comment]
On Sat, 15 Sep 2018 17:28:23 -0700
evilbunny2008 <notifications@github.com> wrote:

> I installed your skin and thought I must have failed, but next
> morning it was working and I hadn't changed a thing.
> 
> As for the next lines after the first try, it got on with other
> weewx'y things, no data received and no third attempt etc...
> 

Original uradmon.py code regarding retires still on here
Odd behaviour after a restart after the weather station dropped its
link to /dev/vpro

multiple attempts to insert same data into the database by uradmon



Sep 17 17:37:07 banksia weewx[6814]: engine: Initializing weewx version 3.8.0
Sep 17 17:37:07 banksia weewx[6814]: engine: Using Python 2.7.13 (default, Nov 24 2017, 17:33:09) #012[GCC 6.3.0 20170516]
Sep 17 17:37:07 banksia weewx[6814]: engine: Platform Linux-4.9.0-3-686-pae-i686-with-debian-9.4
Sep 17 17:37:07 banksia weewx[6814]: engine: Locale is 'en_AU.UTF-8'
Sep 17 17:37:07 banksia weewx[6814]: engine: pid file is /var/run/weewx.pid
Sep 17 17:37:07 banksia weewx[6825]: engine: Using configuration file /etc/weewx/weewx.conf
Sep 17 17:37:07 banksia weewx[6825]: engine: Loading station type Vantage (weewx.drivers.vantage)
Sep 17 17:37:08 banksia weewx[6825]: engine: StdConvert target unit is 0x10
Sep 17 17:37:08 banksia weewx[6825]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=prefer_hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=prefer_hardware, windrun=prefer_hardware, heatindex=prefer_hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=prefer_hardware, inDewpoint=prefer_hardware, ET=prefer_hardware, altimeter=prefer_hardware, cloudbase=prefer_hardware
Sep 17 17:37:08 banksia weewx[6825]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Sep 17 17:37:08 banksia weewx[6825]: uradmon: service version is 0.1.2
Sep 17 17:37:08 banksia weewx[6825]: uradmon: archive_interval in seconds is 300
Sep 17 17:37:08 banksia weewx[6825]: uradmon: archive_interval in minutes is 5
Sep 17 17:37:08 banksia weewx[6825]: uradmon: uRADMonitor address is 192.168.79.195
Sep 17 17:37:08 banksia weewx[6825]: engine: Archive will use data binding wx_binding
Sep 17 17:37:08 banksia weewx[6825]: engine: Record generation will be attempted in 'hardware'
Sep 17 17:37:08 banksia weewx[6825]: engine: Using archive interval of 300 seconds (specified by hardware)
Sep 17 17:37:08 banksia weewx[6825]: engine: Using binding 'wx_binding' to database 'weewx'
Sep 17 17:37:08 banksia weewx[6825]: manager: Starting backfill of daily summaries
Sep 17 17:37:09 banksia weewx[6825]: restx: StationRegistry: Station will be registered.
Sep 17 17:37:09 banksia weewx[6825]: restx: Wunderground: Posting not enabled.
Sep 17 17:37:09 banksia weewx[6825]: restx: PWSWeather: Data for station BEELBANG will be posted
Sep 17 17:37:09 banksia weewx[6825]: restx: CWOP: Data for station VK2XSE will be posted
Sep 17 17:37:09 banksia weewx[6825]: restx: WOW: Data for station 509036046 will be posted
Sep 17 17:37:09 banksia weewx[6825]: restx: AWEKAS: Posting not enabled.
Sep 17 17:37:09 banksia weewx[6825]: engine: Starting up weewx version 3.8.0
Sep 17 17:37:09 banksia weewx[6825]: engine: Clock error is -1.04 seconds (positive is fast)
Sep 17 17:37:09 banksia weewx[6825]: uradmon: connection attempt 1 to 192.168.79.195
Sep 17 17:37:09 banksia weewx[6825]: uradmon: 192.168.79.195 responded on attempt 1
Sep 17 17:37:09 banksia weewx[6825]: uradmon:  record is {'uvolt': 382, 'upm25': 2, 'unoise': 33.73, 'uch2o': 0.01, 'uhum': 35.17, 'uvoc': 153351, 'usUnits': 16, 'uptime': 176440, 'ucpm': 22, 'uco2': 402, 'interval': 5, 'dateTime': 1537169829, 'utemp': 18.88, 'upres': 100393}
Sep 17 17:37:09 banksia weewx[6825]: manager: Added record 2018-09-17 17:37:09 AEST (1537169829) to database 'uradmon'
Sep 17 17:37:09 banksia weewx[6825]: manager: Added record 2018-09-17 17:37:09 AEST (1537169829) to daily summary in 'uradmon'
Sep 17 17:37:09 banksia weewx[6825]: manager: Added record 2018-09-17 17:20:00 AEST (1537168800) to database 'weewx'
Sep 17 17:37:09 banksia weewx[6825]: manager: Added record 2018-09-17 17:20:00 AEST (1537168800) to daily summary in 'weewx'
Sep 17 17:37:10 banksia weewx[6825]: uradmon: connection attempt 1 to 192.168.79.195
Sep 17 17:37:10 banksia weewx[6825]: uradmon: 192.168.79.195 responded on attempt 1
Sep 17 17:37:10 banksia weewx[6825]: uradmon:  record is {'uvolt': 382, 'upm25': 2, 'unoise': 33.73, 'uch2o': 0.01, 'uhum': 35.17, 'uvoc': 153351, 'usUnits': 16, 'uptime': 176440, 'ucpm': 22, 'uco2': 402, 'interval': 5, 'dateTime': 1537169830, 'utemp': 18.88, 'upres': 100393}
Sep 17 17:37:10 banksia weewx[6825]: manager: Added record 2018-09-17 17:37:10 AEST (1537169830) to database 'uradmon'
Sep 17 17:37:10 banksia weewx[6825]: manager: Added record 2018-09-17 17:37:10 AEST (1537169830) to daily summary in 'uradmon'
Sep 17 17:37:10 banksia weewx[6825]: manager: Added record 2018-09-17 17:25:00 AEST (1537169100) to database 'weewx'
Sep 17 17:37:10 banksia weewx[6825]: manager: Added record 2018-09-17 17:25:00 AEST (1537169100) to daily summary in 'weewx'
Sep 17 17:37:10 banksia weewx[6825]: uradmon: connection attempt 1 to 192.168.79.195
Sep 17 17:37:10 banksia weewx[6825]: uradmon: 192.168.79.195 responded on attempt 1
Sep 17 17:37:10 banksia weewx[6825]: uradmon:  record is {'uvolt': 382, 'upm25': 2, 'unoise': 33.73, 'uch2o': 0.01, 'uhum': 35.17, 'uvoc': 153351, 'usUnits': 16, 'uptime': 176441, 'ucpm': 22, 'uco2': 402, 'interval': 5, 'dateTime': 1537169830, 'utemp': 18.88, 'upres': 100393}
Sep 17 17:37:10 banksia weewx[6825]: manager: Unable to add record 2018-09-17 17:37:10 AEST (1537169830) to database 'uradmon': (1062, "Duplicate entry '1537169830' for key 'PRIMARY'")
Sep 17 17:37:10 banksia weewx[6825]: manager: Added record 2018-09-17 17:30:00 AEST (1537169400) to database 'weewx'
Sep 17 17:37:10 banksia weewx[6825]: restx: StationRegistry: Published record 2018-09-17 17:20:00 AEST (1537168800)
Sep 17 17:37:10 banksia weewx[6825]: manager: Added record 2018-09-17 17:30:00 AEST (1537169400) to daily summary in 'weewx'
Sep 17 17:37:10 banksia weewx[6825]: restx: PWSWeather: Published record 2018-09-17 17:20:00 AEST (1537168800)
Sep 17 17:37:10 banksia weewx[6825]: uradmon: connection attempt 1 to 192.168.79.195
Sep 17 17:37:10 banksia weewx[6825]: uradmon: 192.168.79.195 responded on attempt 1
Sep 17 17:37:10 banksia weewx[6825]: uradmon:  record is {'uvolt': 382, 'upm25': 2, 'unoise': 33.73, 'uch2o': 0.01, 'uhum': 35.17, 'uvoc': 153351, 'usUnits': 16, 'uptime': 176441, 'ucpm': 22, 'uco2': 402, 'interval': 5, 'dateTime': 1537169830, 'utemp': 18.88, 'upres': 100393}
Sep 17 17:37:10 banksia weewx[6825]: manager: Unable to add record 2018-09-17 17:37:10 AEST (1537169830) to database 'uradmon': (1062, "Duplicate entry '1537169830' for key 'PRIMARY'")
Sep 17 17:37:10 banksia weewx[6825]: manager: Added record 2018-09-17 17:35:00 AEST (1537169700) to database 'weewx'
Sep 17 17:37:11 banksia weewx[6825]: restx: CWOP: Published record 2018-09-17 17:30:00 AEST (1537169400)
Sep 17 17:37:11 banksia weewx[6825]: manager: Added record 2018-09-17 17:35:00 AEST (1537169700) to daily summary in 'weewx'
Sep 17 17:37:11 banksia weewx[6825]: restx: PWSWeather: Published record 2018-09-17 17:25:00 AEST (1537169100)
Sep 17 17:37:11 banksia weewx[6825]: engine: Starting main packet loop.
Sep 17 17:37:11 banksia weewx[6825]: restx: WOW: Published record 2018-09-17 17:20:00 AEST (1537168800)
Sep 17 17:37:12 banksia weewx[6825]: restx: PWSWeather: Published record 2018-09-17 17:30:00 AEST (1537169400)
Sep 17 17:37:12 banksia weewx[6825]: restx: WOW: Published record 2018-09-17 17:35:00 AEST (1537169700)
Sep 17 17:37:13 banksia weewx[6825]: restx: PWSWeather: Published record 2018-09-17 17:35:00 AEST (1537169700)
Sep 17 17:40:15 banksia weewx[6825]: uradmon: connection attempt 1 to 192.168.79.195
Sep 17 17:40:15 banksia weewx[6825]: uradmon: 192.168.79.195 responded on attempt 1
Sep 17 17:40:15 banksia weewx[6825]: uradmon:  record is {'uvolt': 382, 'upm25': 3, 'unoise': 32.68, 'uch2o': 0.01, 'uhum': 35.39, 'uvoc': 153351, 'usUnits': 16, 'uptime': 176626, 'ucpm': 22, 'uco2': 391, 'interval': 5, 'dateTime': 1537170015, 'utemp': 18.82, 'upres': 100391}
Sep 17 17:40:15 banksia weewx[6825]: manager: Added record 2018-09-17 17:40:15 AEST (1537170015) to database 'uradmon'
Sep 17 17:40:15 banksia weewx[6825]: manager: Added record 2018-09-17 17:40:15 AEST (1537170015) to daily summary in 'uradmon'
Sep 17 17:40:15 banksia weewx[6825]: manager: Added record 2018-09-17 17:40:00 AEST (1537170000) to database 'weewx'
Sep 17 17:40:15 banksia weewx[6825]: manager: Added record 2018-09-17 17:40:00 AEST (1537170000) to daily summary in 'weewx'
Sep 17 17:40:16 banksia weewx[6825]: restx: CWOP: Published record 2018-09-17 17:40:00 AEST (1537170000)
Sep 17 17:40:16 banksia weewx[6825]: restx: PWSWeather: Published record 2018-09-17 17:40:00 AEST (1537170000)
Sep 17 17:40:24 banksia weewx[6825]: cheetahgenerator: Generated 17 files for report StandardReport in 8.82 seconds
Sep 17 17:40:26 banksia weewx[6825]: imagegenerator: Generated 12 images for StandardReport in 1.72 seconds
Sep 17 17:40:26 banksia weewx[6825]: copygenerator: copied 9 files to /var/www/weewx
Sep 17 17:40:28 banksia weewx[6825]: cheetahgenerator: Generated 1 files for report Data in 1.20 seconds
Sep 17 17:40:29 banksia weewx[6825]: cheetahgenerator: Generated 1 files for report Inigo in 1.00 seconds
Sep 17 17:40:29 banksia weewx[6825]: cheetahgenerator: Generated 1 files for report uradmon in 0.46 seconds

**Comment by glennmckechnie** [comment]
That looks suspicously like there are multiple versions running.

Check the weewx.conf file and make sure that there is only 1 entry for  **user.uradmon.UradMon**
Currently it adds it to process_services...
process_services = weewx.engine.StdConvert, weewx.engine.StdCalibrate, weewx.engine.StdQC, weewx.wxservices.StdWXCalculate, **user.uradmon.UradMon**

With the original one I had running here I had changed that location to archive_services  (leave yours at process_services for the moment) and I got a similar thing happening.

The important thing is that it only gets called once. f it is called twice the PID doesn't necessarily change (I'm attempting to confirm that from my logs)

Anyway, there should be only one call to it.
wee_extension --uninstall=XXX should remove all the previous config entries. I assume you ran the unistall between updates?

**Comment by lizdodd** [comment]
On Mon, 17 Sep 2018 08:52:05 +0000 (UTC)
Glenn <notifications@github.com> wrote:

> That looks suspicously like there are multiple versions running.
> 
> Check the weewx.conf file and make sure that there is only 1 entry
> for  user.uradmon.UradMon Currently it adds it to process_services...
> process_services = weewx.engine.StdConvert,
> weewx.engine.StdCalibrate, weewx.engine.StdQC,
> weewx.wxservices.StdWXCalculate, user.uradmon.UradMon
> 
> With the original one I had running here I had changed that location
> to archive_services  (leave yours at process_services for the moment)
> and I got a similar thing happening.
> 
> The important thing is that it only gets called once. f it is called
> twice the PID doesn't necessarily change (I'm attempting to confirm
> that from my logs)
> 
> Anyway, there should be only one call to it.
> wee_extension --uninstall=XXX should remove all the previous config
> entries. I assume you ran the unistall between updates?
> 

Just on a restart it does this, here's another archive cycle

Sep 17 18:55:32 banksia weewx[6825]: copygenerator: copied 0 files
to /var/www/weewx/uradmon 
Sep 17 19:00:15 banksia weewx[6825]: uradmon: connection attempt 1 to
192.168.79.195 
Sep 17 19:00:15 banksia weewx[6825]: uradmon: 192.168.79.195 responded
on attempt 1 
Sep 17 19:00:15 banksia weewx[6825]: uradmon:  record is {'uvolt': 383,
'upm25': 2, 'unoise': 30.25, 'uch2o': 0.04, 'uhum': 39.65, 'uvoc':
97940, 'usUnits': 16, 'uptime': 181429, 'ucpm': 10, 'uco2': 461,
'interval': 5, 'dateTime': 1537174815, 'utemp': 16.06, 'upres': 100435}
Sep 17 19:00:15 banksia weewx[6825]: manager: Added record 2018-09-17
19:00:15 AEST (1537174815) to database 'uradmon'


which looks like it was trying to lay catch up before. The main system
missed 4 archive cycles, and uradmon tried to catch up too, but doesn't
have any stored data, so gives them all the same time stamp.

**Comment by evilbunny2008** [comment]
> which looks like it was trying to lay catch up before. The main system missed 4 archive cycles, and uradmon tried to catch up too, but doesn't have any stored data, so gives them all the same time stamp.

It may be useful on out of normal archive record processing (aka playing catch up) to pull from the uradmon API rather than getting the current record from the device itself.

**Comment by glennmckechnie** [comment]
The retry logic has been fixed.
The timeouts are linked to the [wifi version](https://www.uradmonitor.com/topic/local-access-unit-can-fail-to-respond-to-local-json-queries/)
The discrepancies with the uradmon website values could be fixed by adhering to the API - but that requires time that I (still) don't have.
Code should now under weewx4 (python3) as well as weewx3 (python 2.7 )
